dbt_project:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', '127.0.0.1') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'postgres') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'adminweather123') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'weather_db') }}"
      schema: public
      threads: 1
  target: dev